number_of_data_points: [ 800, 1600, 3200, 6400 ]
number_of_features: [ [ 4, 2 ], [ 4, 4 ], [ 4, 8 ], [ 4, 4, 4 ] ]
number_of_outputs: [ 1,2,4,8 ]
number_of_models: [5 ,10]
concept_drifts: [ 0, 1, 2, 4, 8, 16 ]
data_drifts: [ 0, 1, 2, 4, 8 ]
noise_var: [ 0.0, 0.001, 0.01 , 0.1 ]
base_seed: [ 42 ]
drift_blocking_mode: [ false, true ]


fixed:
  continuous_time: true
  min_severity: 0.1
  max_severity: 0.6
  root_distros: [ 1, 1, 1, 1 ]